/*Atividade 1*/

CREATE TABLE produtos(
    id NUMBER GENERATED by default on null as IDENTITY,
    descricao VARCHAR(50) NOT NULL,
    status NUMBER(1) NOT NULL,
    cadastro TIMESTAMP NOT NULL,
    quantidadeEstoque NUMBER(10,2),
    PRIMARY KEY(id)
);

INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 1', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 2', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 3', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 4', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 5', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 6', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 7', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 8', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 9', 1, '01-01-2000', 10);
INSERT INTO produtos (descricao, status, cadastro, quantidadeEstoque) 
VALUES ('Produto 10', 1, '01-01-2000', 10);

SELECT * FROM produtos;
