/*Atividade 2*/

CREATE TABLE produtoPreco(
    id NUMBER GENERATED by default on null as IDENTITY,
    idProduto NUMBER NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    status NUMBER(1) NOT NULL,
    cadastro TIMESTAMP NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (idProduto) REFERENCES produtos(id)
);

INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (2, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (3, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (4, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (5, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (6, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (7, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (8, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (9, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (10, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (11, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (1, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (2, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (3, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (4, 100.00, 1, '01-01-2000');
INSERT INTO produtoPreco (idProduto, valor, status, cadastro) 
VALUES (5, 100.00, 1, '01-01-2000');

SELECT * FROM produtoPreco;
