CREATE TABLE matriculas(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_aluno NOT NULL,
    id_curso NOT NULL,
    media Decimal(4,2) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (id_aluno) REFERENCES alunos(id),
    FOREIGN KEY (id_curso) REFERENCES cursos(id)
);